
baseurl: ""
markdown: kramdown
future: true


markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
        
exclude: ['README.md']
authors:
    deepak_sama:
        display_name:Deepak Reddy Sama